# Generated by Django 2.0.6 on 2018-06-24 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import keja.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_bio', models.TextField(blank=True, null=True)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to=keja.models.profile_image)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.BigIntegerField(blank=True)),
                ('place_from', models.TextField(choices=[('Juja', 'Juja'), ('Nairobi', 'Nairobi'), ('Kahawa', 'Kahawa')], help_text="Caretaker's place from", max_length=1)),
                ('university_name', models.TextField(choices=[('JKUAT', 'Jommo Kenyatta University of Agriculture and technology'), ('UON', 'University of Nairobi'), ('KU', 'Kenyatta University')], help_text='Around which university is the house located', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField()),
                ('room_type', models.TextField(choices=[('Two sharing', 'Two sharing'), ('Four sharing', 'Four sharing'), ('Hostel', 'Hostel'), ('Bedsitter', 'Bedsitter'), ('One bedroom', 'One bedroom'), ('Two bedroom', 'Two bedroom'), ('Three bedroom', 'Three bedroom')], help_text='The type of room eg Bedsitter or One bedroom', max_length=3)),
                ('house_photo', models.FileField(upload_to=keja.models.house_photo)),
                ('house_video', models.FileField(blank=True, null=True, upload_to=keja.models.house_video)),
                ('floor_number', models.IntegerField(help_text='How many floors including ground floor')),
                ('plot_area', models.BigIntegerField(help_text='The total area of the plot', null=True)),
                ('security_company', models.CharField(max_length=100, null=True)),
                ('special_features', models.TextField(null=True)),
                ('rating', models.IntegerField(default=0, null=True)),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='keja.Caretaker')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('review_content', models.TextField()),
                ('publish_date', models.DateTimeField(verbose_name='Date published')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='keja.House')),
            ],
        ),
    ]
